---

- name: Install Homebrew via the curl one-liner
  shell: /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  args:
    creates: /usr/local/bin/brew

- name: Update and upgrade homebrew
  homebrew: update_homebrew=yes upgrade_all=yes

- name: See that 'brew list' works
  command: brew list

- name: Install homebrew cask
  homebrew_tap: name=caskroom/cask

- name: See that 'brew cask list' works
  command: brew cask list
